### ISSUE TITLE
Does texlab look in my ~/texmf?

### ISSUE THREAD

**Issue by godfrey-cw** [latex-lsp/texlab#100]
More of a question really. I typically keep all my style files in that directory and don't seem to be getting completion support for environments, macros etc. defined there. 

Second question: even if `texlab` doesn't automatically look there, is there a way to add that directory to the current workspace?

Many thanks for all of your work!

**Comment by clason** [comment]
Note that this path can be configured (I put mine in `~/Library/texmf`). The programmatic way of getting that is via `kpsewhich -var-value TEXMFHOME` from the command line.

**Comment by efoerster** [comment]
Before version [1.2.0](https://github.com/latex-lsp/texlab/blob/master/CHANGELOG.md#120---23072019), TexLab indexed all package/style files in all `TEXMF` directories. Since this was a little too time consuming, we removed this mechanism. Currently, we use a [script](https://github.com/latex-lsp/latex-completion-data) to scan all files of `texlive-full` beforehand and store it and a cache.
 
However, I think we should add it back to index user-defined files and/or missing packages. We could keep the pre-computed completion data and add the indexing mechanism on top of it.

**Comment by clason** [comment]
I think scanning TEXMFHOME in addition to a cached texlive-full would be a good compromise. (Texlive does add new packages continuously, but rerunning the script once in a while should be enough. Of course, if you wanted to be really fancy about it, you could separate the database from the binary and make texlive check for and download updated versions...)

**Comment by pfoerster** [comment]
@godfrey-cw Can you try the latest commit on the master branch?
TexLab now adds local packages that are not part of the global package cache to the workspace using the `kpsewhich` database. This should provide completion for most commands without having to reimplement the scanning mechanism in Rust.

**Comment by godfrey-cw** [comment]
Wonderful! Just recompiled and I'm getting completions labelled "`user-defined`" for my own macros now.

**Comment by efoerster** [comment]
This feature is included in the v1.9.0 release. Closing this now, because I think the feature that @pfoerster implemented is the best compromise at the moment.
