### ISSUE TITLE
High CPU use and multiple request timeouts while editing in a directory with many tex files

### ISSUE THREAD

**Issue by gustafla** [latex-lsp/texlab#1005]
I'm running texlab 5.12.2 (texlab-git AUR package) with helix 23.10.

My configuration is
```
[language-server.texlab]
config.texlab.build.onSave = true
config.texlab.build.args = ["-pdf", "%f"]
```

The problem starts when I'm editing a .tex file in a working directory with about 80 other unrelated .tex files. LSP requests just pile up, CPU fan is going wild and latency for builds becomes very high. Messages about requests timing out start to appear. I don't have much clue to what actually causes this.

**Comment by pfoerster** [comment]
@gustafla The problem starts when I'm editing a .tex file in a working directory with about 80 other unrelated .tex files.

Probably, the 80 files in the same directory are the problem. Is every one of these files self-contained or do some of the files reference each other.

> Messages about requests timing out start to appear.

Probably, `publishDiagnostics` is the culprit. It will spam because the server resends 80 notifications after every edit.

**Comment by gustafla** [comment]
This does not seem to affect me any more. I don't know if it was a code change or hardware change (I upgraded from 32 thread CPU to 16 with more cache).
