### ISSUE TITLE
project detection: .latexmkrc in higher level parent directory

### ISSUE THREAD

**Issue by daviehh** [latex-lsp/texlab#1118]
There have been bug fix concerning the `~/.latexmkrc` in the home folder, but it seems that the .latexmkrc file in higher level parent director can also override the detection. Expected behavior or bug? Thanks!

e.g. /path/to/ contains the .latexmkrc, but files in /path/to/some/dir/a.tex would treat /path/to as the project folder

<img width="582" alt="Screenshot 2024-05-11 at 14 49 53" src="https://github.com/latex-lsp/texlab/assets/25255906/89f68383-7beb-45f3-ad02-221a6a10e70d">

.latexmkrc file here only has one line `$pdf_mode = 1;` for testing

**Comment by pfoerster** [comment]
> There have been bug fix concerning the ~/.latexmkrc in the home folder, but it seems that the .latexmkrc file in higher level parent director can also override the detection. Expected behavior or bug? 

This is currently the expected behavior and is required to handle cases like these
```
.latexmkrc
src/
    main.tex
    subfolder/
        child1.tex
        child2.tex
```

where the directory of the main source file is not equal to the compile directory.

Unfortunately, the (working) directory passed by the editor cannot be relied upon in most cases (especially with editors like `vim`)

**Comment by daviehh** [comment]
thanks for the explanation!
