### ISSUE TITLE
Difficulties to install for Sublime Text 3

### ISSUE THREAD

**Issue by LukasCBossert** [latex-lsp/texlab#127]
Hey - 
`texlab` seems to be a very cool thing but unfortunately I am unable to install it on 
- macOS 10.15.2 (Mojave)
- Sublime Text 3 (3.2.2)
with latest LSP from the Package Manager and texlab 1.8.0 (via homebrew).

I miss some detailed information on the installation process - I cannot figure out what I missed. 
From the website it seems like no further settings are necessary after the installation (via homebrew etc.) But LaTeX is not listed in the LSP list, is it due that LSP does not support LaTeX, yet? 

After some googling I finally found https://lsp.readthedocs.io/en/latest/#latex and I added 
```
"texlab": {
  "command": ["texlab"],
  "languages": [{
    "scopes": ["text.tex.latex"],
    "syntaxes": ["Packages/LaTeX/LaTeX.sublime-syntax"],
    "languageId": "latex"
  }, {
    "scopes": ["text.bibtex"],
    "syntaxes": ["Packages/LaTeX/Bibtex.sublime-syntax"],
    "languageId": "bibtex"
  }],
  "enabled": true
}
```
but still no luck.

How do I get `LaTeX.sublime-syntax` into the LaTeX folder? I would think that this is done via the installation process?

I am happy for any help and further details how I can get it up and running on sublime.
Thanks.

**Comment by pfoerster** [comment]
> I miss some detailed information on the installation process - I cannot figure out what I missed.
From the website it seems like no further settings are necessary after the installation (via homebrew etc.)

The Homebrew package only provides the executable of the language server. As there are a lot of possible clients that can be used with the server (see https://microsoft.github.io/language-server-protocol/implementors/tools/), it is up to the user to configure the editor.

 > But LaTeX is not listed in the LSP list, is it due that LSP does not support LaTeX, yet?

LSP is an universal protocol that can work with any programming language. LaTeX is no exception.
The problem is probably located on the side of Sublime.

> After some googling I finally found https://lsp.readthedocs.io/en/latest/#latex and I added

I tried these instructions too and they do not seem to working for me, either.
I don't think that the LSP plugin for Sublime actually calls our language server so I think it is probably a documentation issue. Can you open an issue on the [Sublime LSP](https://github.com/sublimelsp/LSP) repository, please? I would be happy to provide some instructions for Sublime users on our [website](https://texlab.netlify.com) once the issue has been resolved.

**Comment by jwortmann** [comment]
Hi, I just saw this issue and I hope that I can help you. I use TexLab in Sublime Text and it works fine for me (I'm on Windows though, but there shouldn't be a reason why it would not work on macOS). The documentation for the LSP package is a bit unclear at the moment, but I made a PR to rewrite some parts of it and meanwhile you can see it [here](https://github.com/jwortmann/LSP/blob/documentation/docs/index.md) until it's merged in master.

So the first thing I can imagine why it wouldn't work is, that you didn't put the configurations under a "clients" key in your settings file. So a mininum example for your `LSP.sublime-settings` file would be this:
```json
{
  "clients": {
    "texlab": {
      "command": ["texlab"],
      "enabled": true,
      "languages": [{
        "languageId": "latex",
        "scopes": ["text.tex.latex"],
        "syntaxes": ["Packages/LaTeX/LaTeX.sublime-syntax"]
      }, {
        "languageId": "bibtex",
        "scopes": ["text.bibtex"],
        "syntaxes": ["Packages/LaTeX/Bibtex.sublime-syntax"]
      }]
    }
  }
}
```

Also remember that you either need to put the texlab executable in a directory that is in your PATH, or alternatively specify the full path to it, e.g. `"command": ["C:/path/to/texlab.exe"]` (on Windows).

> How do I get LaTeX.sublime-syntax into the LaTeX folder?

The `LaTeX.sublime-syntax` file is for LaTeX syntax highlighting, and it is already contained in a basic Sublime Text installation, so there is nothing that you manually need to do here. This basically tells Sublime to start the TexLab server for LaTeX files. (The file is actually contained in a zipped "LaTeX.sublime-package" archive under "Packages" in the installation directory of Sublime Text, but with the way how packages work Sublime can see it on the "Packages/LaTeX/LaTeX.sublime-syntax" path.)

**Comment by LukasCBossert** [comment]
Thank you both for the help! Somehow I was able to manage it and `texlab` is now listet in the Sublime LSP-list.

I did two things.
1. Copy the information about `client` as above into the settings-section of LSP
1. copy the `texlab` binary into my texmf-local folder (and run `texhash`).

its working now!
