### ISSUE TITLE
git cargo install fails

### ISSUE THREAD

**Issue by senselessDev** [latex-lsp/texlab#342]
When trying to install via 
`cargo install --git https://github.com/latex-lsp/texlab.git` 
it fails with 
```
error[E0432]: unresolved import `syn::export`
 --> crates/jsonrpc_derive/src/lib.rs:7:11
  |
7 | use syn::{export::TokenStream2, *};
  |           ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `jsonrpc-derive`.
```

Seems like other projects experience a similar problem with the latest `syn` update as you can see [here](https://github.com/nushell/nushell/pull/2868). Their solution was to pin to the older 1.0.57, although the proper solution seems to be [this](https://github.com/frondeus/test-case/issues/60#issuecomment-755228907). 

But from my understanding, it has to be solved in [jsonrpc](https://github.com/paritytech/jsonrpc), right?

**Comment by pfoerster** [comment]
Thanks for the detailed report. The issue is due to the fact that `cargo install --git` does not use the `Cargo.lock` file by default in which we specify an older version. You can try running `cargo install --locked --git https://github.com/latex-lsp/texlab.git` to see if it fixes the problem. I should update the README to include the `--locked` flag.

> But from my understanding, it has to be solved in jsonrpc, right?

The `jsonrpc` crate is a local crate that is different from Parity JSON-RPC. You can find it in the `crates` folder. At the moment, I am removing this crate in favor of the library that Rust Analyzer uses so procedural macros won't be required anymore.

**Comment by senselessDev** [comment]
Thank you for your quick reply! I can confirm that using the `Cargo.lock` fixed it.

> The `jsonrpc` crate is a local crate that is different from Parity JSON-RPC. You can find it in the `crates` folder. At the moment, I am removing this crate in favor of the library that Rust Analyzer uses so procedural macros won't be required anymore.

Whoops, it seems I was too quick on this one ;) But thanks for clarifying.
