### ISSUE TITLE
v2.2.1 release for macOS fails to start

### ISSUE THREAD

**Issue by fannheyward** [latex-lsp/texlab#344]
The latest v2.2.1 release for macOS can't start. https://github.com/latex-lsp/texlab/releases/download/v2.2.1/texlab-x86_64-macos.tar.gz

Looks like it's a failed tar.gz

**Comment by pfoerster** [comment]
Thanks for the report. The `tar.gz` looks indeed somehow broken. I have updated the release. Can you check if it works now, please? Unfortunately I do not have a machine to test this.

**Comment by fannheyward** [comment]
>  I have updated the release

How can I get it?

**Comment by pfoerster** [comment]
>How can I get it?

Here:
https://github.com/latex-lsp/texlab/releases/download/v2.2.1/texlab-x86_64-macos.tar.gz

**Comment by fannheyward** [comment]
Still failed. `texlab-x86_64-macos.tar.gz` v2.2.1 is smaller than v.2.2.0 and early version.

**Comment by fannheyward** [comment]
`cargo build --release` is OK.  `file texlab` result: `texlab: Mach-O 64-bit executable x86_64`, the release is `texlab: data`.

**Comment by fannheyward** [comment]
`tar -czvf texlab-x86_64-macos.tar.gz -C target/release texlab` creates `texlab-x86_64-macos.tar.gz` 11M.

**Comment by pfoerster** [comment]
The problem seems to be related to this one: https://github.community/t/bizarre-issue-with-tar-archive-for-macos-build/145377
Can you try the following build please:

 https://github.com/latex-lsp/texlab/releases/download/v2.2.1/texlab-x86_64-macos.tar.gz
 
 The file size now makes sense in comparison to the other files. In the CI script I use now GNU tar on macOS.

**Comment by fannheyward** [comment]
It works.
