### ISSUE TITLE
Allow for passing extra arguments to latexindent

### ISSUE THREAD

**Issue by falk-h** [latex-lsp/texlab#365]
latexindent can do some more advanced formatting than just indenting, like wrapping lines, putting each sentence on its own line, et cetera, if given the `-m` option. It can also take settings from a specified file, create backups and take inline settings. I feel like TexLab should have an option for extra arguments to pass to latexindent, or alternatively, a couple of options that mirror relevant latexindent flags.

**Comment by khaveesh** [comment]
@pfoerster, How do I pass extra arguments to latexindent? I searched and couldn't find any option in the 3.0 release.

**Comment by clason** [comment]
Don't you configure latexindent via a `localSettings.yaml` in the project directory?

**Comment by khaveesh** [comment]
@clason, I indeed configure it like that. But this issue was requesting for an option to pass arguments. And the 3.0 release was said to close this issue.

And as to why this option may be useful:
The global configuration path for latexindent is quite complex. You need to have a indentconfig.yaml in home directory which contains the paths of any yaml file that you want it to parse for options. I need to use this convoluted setup just to globally change the indentation from tabs to spaces. Instead if texlab could pass extra argument to latexindent, I could avoid this whole setup for just a single change in the options.

**Comment by pfoerster** [comment]
@khaveesh Which flags do you need exactly (I am assuming `--local`)? I am bit hesistant to expose every flag of `latexindent` because most of those flags won't work with the way we call `latexindent` (the file is sent to `stdin` of `latexindent`). However, I am fine with exposing some required flags as options. Just tell me, which flags you need and I will add them for the next release.

**Comment by khaveesh** [comment]
Actually, I found a simpler workaround:
- Create an executable script that calls latexindent(using full path) with all the command-line options you want. 
- Rename this executable as latexindent.
- Put this executable ahead of the original latexindent in the `$PATH`. 
- Now, texlab uses this latexindent executable, and thus formats it with all the options you had configured.

**Comment by falk-h** [comment]
Back when I opened this issue I also created a fork where I added the `-l` and `-m` flags.

**Comment by pfoerster** [comment]
As of `texlab 3.1.0`, the `-l` and `-m` flags can now be configured using via the LSP options, see https://github.com/latex-lsp/texlab/blob/master/docs/options.md#texlablatexindentlocal for a reference.

**Comment by Hs293Go** [comment]
@pfoerster Is there any chance we get LSP options to configure the `-g` or `-c` flags as well? They control logging behavior (https://github.com/cmhughes/latexindent.pl/issues/198) and configuring one of these flags is the only way to prevent latexindent from leaving `indent.log`s inside your source tree --- this outright **cannot** be done in the `localSettings.yaml` file according to latexindent's author: https://tex.stackexchange.com/a/144264. 

Apologise in advance for resurrecting this issue, but the title of this issue perfectly encompasses my problem.

**Comment by TomLebeda** [comment]
+1 for what @pfoerster wrote, I'm dealing with exactly the same issue.
