### ISSUE TITLE
 build on save not working in version 3.0.0

### ISSUE THREAD

**Issue by yochem** [latex-lsp/texlab#427]
Hi maintainers,

I've just updated texlab to version 3.0.0, but it seems like the option build on save is not working anymore, while it did work in a previous version of texlab. Running the `:TexlabBuild` command works as expected.

I could not find any logs of texlab, so please let me know if texlab logs actions and where I can find these log files.

Versions:
- NVIM v0.5.0-dev+bb3372792
- [neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) master (0699e6c..d23816b)
- texlab version 3.0.0

Config:
```lua
lsp.texlab.setup {
    root_dir = lsp.util.root_pattern("."),
    settings = {latex = {build = {onSave = true}}}
}
```

Let me know if I can provide more information. Thank you in advance for looking into it.

**Comment by pfoerster** [comment]
Thanks for the report. The build on save setting has been removed in texlab 3.0.0 in favor of the continuous build feature provided by most build systems. If you are using `latexmk`, I recommend adding the `-pvc` flag to your `texlab.build.args` array (if you are not using a previewer, you also need to set `-view=none`). Usually, `latexmk` is better at figuring those things out. Also, be sure to set the new setting `texlab.build.isContinuous` to `true`.

**Comment by LDAP** [comment]
The problem I have been facing is that TexLab does not kick of the latexmk build. I had to send the custom command `textDocument/build`.

**Comment by clason** [comment]
Surely that is by design? I for one _don't_ want `texlab` building on save since I handle that myself.

**Comment by LDAP** [comment]
In my opinion the build on save feature should be reintroduced. This allows disabling the behavior if a custom build system is required but allows an all-in-one solution only using TexLab.

**Comment by clason** [comment]
I'm not against having an option to trigger the `build` custom request automatically on first save, but I strongly feel that it would have to be opt-in.

**Comment by yochem** [comment]
```lua
lsp.texlab.setup {
    root_dir = lsp.util.root_pattern("."),
    settings = {
        build = {
            args = { "-pvc", "-view=pdf", "%f" },
            isContinuous = true
        }
    }
}
```

Changed my config in this, but it is still not working. Running `latexmk -pvc -view=pdf main.tex` on the command line works as expected though. Is there something wrong with the config?

**Comment by clason** [comment]
If I understand correctly, you need to trigger building **manually** at least once; after that, the document will be _re_built every time you save.

**Comment by clason** [comment]
(And you don't need to specify the `root_dir`; unless you have a very special setup (multiple project dirs), the default should work out of the box.)

**Comment by yochem** [comment]
> If I understand correctly, you need to trigger building manually at least once; after that, the document will be _re_built every time you save.

Thank you! That is indeed the case.

> (And you don't need to specify the root_dir; unless you have a very special setup (multiple project dirs), the default should work out of the box.)

Yeah I don't know why I specified it because it works as expected indeed.

**Comment by pfoerster** [comment]
> In my opinion the build on save feature should be reintroduced. This allows disabling the behavior if a custom build system is required but allows an all-in-one solution only using TexLab.

As @clason has already said, the goal of `texlab` is not necessarily to be an all-in-one solution. In the case of building, launching a shell with `latexmk -pvc` is almost always better (and especially if you use a terminal-based editor) because you still have the option to easily cancel the build (which is something that is very hard for `texlab` to do because there are no good crates currently for killing an entire process tree; that's why we removed the cancel feature until we find a better solution as it did not work as intended) and there is little benefit of having this feature inside of texlab because from the view of texlab it does almost nothing when building. It reads the configuration, launches a process and redirects the output to the LSP layer but there is no additional logic, for example, `latexmk` figures out which files need to be recompiled.

**Comment by pfoerster** [comment]
Note that the VSCode extension still has this feature (with a renamed setting) and adding this feature to the server would break the VSCode extension because of `texlab.build.forwardSearchAfter`. `texlab.build.forwardSearchAfter` was moved to the VSCode extension because there is no reliable way to get the position of the cursor using LSP so it does not make sense to implement this feature in the server.

**Comment by clason** [comment]
(This is a bit orthogonal to this issue, but I think it might be useful to add a setting -- here or in the extension -- to call `forwardSearch` after a successful(!) manual(!) build to update the viewer (and optionally jump to the cursor position?).)

**Comment by pfoerster** [comment]
> (This is a bit orthogonal to this issue, but I think it might be useful to add a setting -- here or in the extension -- to call forwardSearch after a successful(!) manual(!) build to update the viewer (and optionally jump to the cursor position?).)

That's actually already implemented with this setting. See here:

https://github.com/latex-lsp/texlab-vscode/blob/master/src/extension.ts#L203

But it somehow is broken (again) (see https://github.com/latex-lsp/texlab-vscode/issues/434). I need to take a look at this.
