### ISSUE TITLE
Reporting imaginary errors

### ISSUE THREAD

**Issue by hsmyers** [latex-lsp/texlab#433]
Given:

`\newglossaryentry{tabula negotiorum}{
  type=Nouns,
  first={tabula negotiorum},
  name={tabula negotiorum},
  description={\Parse{engagement tablet}}
}
`
TexLab reports `Missing "}" inserted texlab`  incorrectly. It is not up to texlab to forbid multiple word gloss entries. Give this _**'error'**_ a number and let me turn it off. For that matter, give everything a number and let me decide what should or should not be reported. For reference see _**Lint**_ of any variety.

**Comment by clason** [comment]
That sounds like a parser error (probably didn't expect the keyword style arguments) that can be fixed; no reason to suppose a giant conspirancy to prevent you from writing glossary entries...

**Comment by hsmyers** [comment]
You imagine conspiracy where I describe error!? If errors were user-side
configurable I could actually use texlab to my benefit. Or was this humor?

**Comment by hsmyers** [comment]
No argument about the ostrich approach. That said, taking the Lint approach
is still useful. as an example consider this case. This report is white
noise until the parser fix allows multiple words in the entry. You allow me
to turn off chktex errors at will, my suggestion would not differ.

**Comment by clason** [comment]
(This is not `chktex` but texlab's internal parser that it uses for all its functionality. And it's not about multiple words -- I believe -- but about the keyword arguments to `newglossaryentry`.)

**Comment by hsmyers** [comment]
Interestingly this works:

\newglossaryentry{electrolyte}{
  type=Nouns,
  name=electrolyte,
  description={solution able to conduct electric current}
}

**Comment by clason** [comment]
Interesting, it's the white space in the glossary entry. That should be fixable.

**Comment by hsmyers** [comment]
LaTeX glossary only requires that given \newglossaryentry{label}, *label*
be unique.And that should be discovered by whatever glossary processor is
used for the project. I.e., you don't need to check/?

**Comment by clason** [comment]
Texlab doesn't use a LaTeX/preprocessor run to parse your source (that would be much too slow) in order to find all the labels, references etc. needed for it to do its job; it uses an internal parser to extract that information. (This parser is completely rewritten for the new version 3.0.0, which is why this suddenly appears now.) 

In particular, it needs to know where the `newglossaryentry` ends so it can start looking for other stuff. This is encoded somewhere in the source (how many arguments, what can be in them, etc.), which apparently doesn't allow for spaces in the label. It's this information (form of `label`) that needs to be fixed/adapted to not error out when there is a space.

**Comment by hsmyers** [comment]
Ah! Sensible. That would make the slowness of change in LaTeX a 'good
thing'. Keeping up, if too fast, can drive you crazy. My second company had
a situation where change requests were made up on the fly based on the
presentation of the previous '*requests*'. This forced a change from 'C' to
C++, changing an object is much easier than changing straight code. That
was long ago, you have my sympathy now!

**Comment by pfoerster** [comment]
As you guys have already guessed correctly, the parser of `texlab` currently does not allow multiple tokens as identifiers in glossary entries (and labels). This is definitely fixable. The error happens because `texlab` only expects a single token and the parser closes the brace group before reading the next token.

> Texlab doesn't use a LaTeX/preprocessor run to parse your source (that would be much too slow)

Before starting this server, I thought about the idea to basically implement a macro expansion engine without the typesetting stuff  but went with the more traditional approach instead because it would be very complicated as one would have to dive quite deep into the TeX internals and performance could be a concern too.

**Comment by clason** [comment]
The only thing guaranteed to parse TeX correctly is... TeX. I don't think reimplementing TeX in Rust -- intriguing as that would be -- is a feasible project...

I believe `newglossaryentry` is conceptually more similar to `cite` (which _does_ allow whitespace/multiple tokens without error) than `label`.

**Comment by hsmyers** [comment]
Hmmm… RustTeX pronounced 'Rustic'—I like it. My belief is that it is
currently written in 'C' so a code translation to Rust is no great stretch
of the imagination. Hopefully with a pickup of speed?

**Comment by cydmium** [comment]
Just to add another data point (and potentially confirm the whitespace issue), I am experiencing the same texlab false error with
`\label{text other_text}`
But I am not experiencing the error with 
`\label{text:other_text}`

**Comment by pfoerster** [comment]
> The only thing guaranteed to parse TeX correctly is... TeX. I don't think reimplementing TeX in Rust -- intriguing as that would be -- is a feasible project...

Well, there is [Tectonic](https://github.com/tectonic-typesetting/tectonic) (which now supports Windows by the way) and they started exporting more functionality in their library crate. I thought about using tectonic as a library to do more (expensive) analysis but I don't think that it is ready yet and it would be another huge dependency besides `citeproc`. In particular, the plans for HTML output seem to be pretty interesting.

**Comment by hsmyers** [comment]
I see multiple instances of incorrect errors where the parser didn't find
what it was looking for. \includegraphics{#1} for example.

**Comment by pfoerster** [comment]
Can you try the latest commit on the master branch and see if it works for you?
Now, `texlab` should parse identifiers with white space in between correctly. In addition to that using `#1` and similar should not trigger an error anymore. Note that there may be a (small) performance regression (because there is more work involved; if it is too bad, please let me know). Besides that, all static analysis errors produced by `texlab` now have a number associated with them.

**Comment by clason** [comment]
Oof, that looks like it was a massive amount of work... 🚀 

Looks good, and I don't notice any major performance regressions. Are the numbers reported via LSP? I don't see them in my client -- just "Missing "}" inserted" or "Unexpected "}"` in this example.

>  I don't think reimplementing TeX in Rust -- intriguing as that would be -- is a feasible project...

I should have specified that reimplementing TeX in Rust is not feasible to do as part of texlab ;) (I know about Tectonic and agree that it is interesting.)

**Comment by clason** [comment]
One thing: It seems you are not distinguishing between types of white spaces? So the parser allows for something like 
```tex
\chapter{foo

bar}
```
which is not allowed by TeX. (Line break is OK; empty line is not.) Distinguishing that might improve performance and make the parser errors more local?

**Comment by pfoerster** [comment]
> Oof, that looks like it was a massive amount of work... rocket

Not that massive but quite significant. Fortunately, the compiler and the tests were very helpful. I started by updating the parser, then the CST structure and then I fixed all reported compiler errors and it mostly worked. Most of the effort was related to the completion. 

>   Are the numbers reported via LSP? I don't see them in my client -- just Missing "}" inserted or Unexpected "}" in this example.

Yes, a `Diagnostic` has a `code` attribute but it looks like some clients do not show it. Even the LSP spec is hinting at it:
```ts
       /**
	 * The diagnostic's code, which might appear in the user interface.
	 */
	code?: integer | string;
```

> I should have specified that reimplementing TeX in Rust is not feasible to do as part of texlab ;) 

Yeah, that's why I quickly abandoned the idea ;)

> (I know about Tectonic and agree that it is interesting.)

Maybe some day it will support HTML output, which would make it quite nice for previewing.

> One thing: It seems you are not distinguishing between types of white spaces? 

Yes, that's correct. I am unsure if handling different types of white space would improve performance. In my experience, making a parser more lax usually helps with performance. It could help with the parser errors but it would involve a bit of additional work as the parser becomes a tiny bit more complex but maybe it's worth it. Note that the parser does not throw away the white space tokens anymore so it can be still be used to detect errors like with the chapter example. The syntax tree itself is lossless now.

**Comment by clason** [comment]
> Yes, a `Diagnostic` has a `code` attribute but it looks like some clients do not show it. Even the LSP spec is hinting at it:

Ah, OK, then I understand this. Neovim LSP doesn't handle this (yet), and I'd prefer to let sleeping dogs lie there ;)

But I'll keep it in mind.

> Yes, that's correct. I am unsure if handling different types of white space would improve performance. In my experience, making a parser more lax usually helps with performance. It could help with the parser errors but it would involve a bit of additional work as the parser becomes a tiny bit more complex but maybe it's worth it. Note that the parser does not throw away the white space tokens anymore so it can be still be used to detect errors like with the chapter example. The syntax tree itself is lossless now.

That makes sense; it was just a thought. Catching empty lines (paragraph breaks in TeX) in tokens may be worth it, but not at the cost of other things or a large effort (if it doesn't actually help internally).

And "lossless syntax tree" sounds like a good thing 😄

**Comment by hsmyers** [comment]
Like every long-time programmer (I'm 70, started in 75') I have rules:

   1. Everything is a parser
   2. No parser is bug-free
   3. No parser is ever finished

These are to be thought of to the meme of '*It's turtles all the way down*'…

--Hugh
p.s. Thanks for the work!

**Comment by pfoerster** [comment]
`texlab 3.1.0` fixes this issue and all static analysis diagnostics now have an error code associated with them :rocket:.

**Comment by hsmyers** [comment]
A quick shout-out of 'Yay'! Availability?

**Comment by pfoerster** [comment]
Which operating system and LSP client / editor are you using? You can either download a release from here (https://github.com/latex-lsp/texlab/releases/tag/v3.1.0) or you can wait a day or two for the package managers to catch up (see the badges in the README). Some editor extensions also download `texlab` automatically for you like the VSCode extension or `coc-texlab`.

**Comment by hsmyers** [comment]
I use both WSL(now with a g) and Windows !0 (bleeding-edge), so I'd be
looking for the Visual Code package.
