### ISSUE TITLE
cannot clean temporary files?

### ISSUE THREAD

**Issue by islercn** [latex-lsp/texlab#434]
i use sublime 4 + texlab 3.0.1, there will be too many .fls file after compilation

if i add "-c" to texlab.build.args, i always get:

LSP-TexLab: Latexmk: Cannot remove file 'xxx.log'
LSP-TexLab: Latexmk: Cannot remove file 'xxx.fls'
LSP-TexLab: Latexmk: Cannot remove file 'xxx.aux'

(no such problem for sublime3 + latextools)

**Comment by pfoerster** [comment]
Thanks for the report. The problem is that `texlab` needs the `aux` and the `log` files to implement some features:
- Diagnostics reporting for compilation errors
- Convert labels to numbers (this information is stored inside the aux file).

`texlab` uses a file watcher to watch for file changes related to the these files. After these files are created or updated, `texlab` reads them and locks them during this duration. So it is not really recommended to clean out those files. Instead, you can change the output directory if you want less clutter in your source directory. Note that you need to update the `texlab.auxDirectory` setting. The Tectonic API could be used in this case for compilation but it is not easy to build on Windows and not feature-complete yet.

**Comment by krisfans** [comment]
Can you provide a new command to clear the auxiliary files so that we can delete the auxiliary files after all the work is completed ?
