### ISSUE TITLE
specify pdf viewer for compilation via LSP

### ISSUE THREAD

**Issue by islercn** [latex-lsp/texlab#436]
to use SumatraPDF as the PDF previewer, i have to create and modify %USERPROFILE%/.latexmkrc

if i can choose the pdf viewer via LSP, like the option "texlab.forwardSearch.executable" for forward search?

after testing, the option "texlab.forwardSearch.executable" is only for forward search, not to view the pdf file after compilation

**Comment by clason** [comment]
See https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md

**Comment by islercn** [comment]
> See https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md

it is not so portable, perhaps it ok that the .latexmkrc file can be allowed to be placed in the program directory, but it is not valid

so allowing users to specify pdf viewer via LSP is also a good choice

**Comment by pfoerster** [comment]
> it is not so portable, perhaps it ok that the .latexmkrc file can be allowed to be placed in the program directory, but it is not valid

At the moment, `texlab` does not control the PDF viewer. Instead, the build system (e. g. `latexmk`) is currently responsible for launching the PDF viewer. Thus, the `latexmkrc` needs to be found by `latexmk` and not `texlab`. `texlab` does not parse (or better execute) this file. I would avoid hard-coding every possible viewer into `texlab` as there is quite some maintenance effort involved. I don' think it should be portable because every user uses some different kind of PDF viewer.

**Comment by clason** [comment]
But you already configure the viewer for forward search, don't you? Wouldn't it be possible to add a callback after (successful) compilation to trigger a forward search?

(Or leave it user definable so they can do whatever they want?)

**Comment by pfoerster** [comment]
> But you already configure the viewer for forward search, don't you? 

Yeah, that would be possible. I think I misread the issue a little bit. I thought that we should include the configuration from the documentation inside `texlab` so the user just specifies `texlab.build.viewer: "sumatra"` for example. I think adding a `texlab.build.viewer.executable` setting seems reasonable. 

> Wouldn't it be possible to add a callback after (successful) compilation to trigger a forward search?

Not exactly. To perform a forward search we need a line number, which is something `texlab` does not know. In past versions, we tried to guess the value but this approach was pretty much tailored to VSCode and not useful in the general case, which is why I moved it to the extension only. I think this feature is valuable but it needs to implemented correctly.

**Comment by pfoerster** [comment]
Concerning the forward search after building, there is https://github.com/microsoft/language-server-protocol/issues/718, which would make it possible to implement this feature.

**Comment by pfoerster** [comment]
`texlab 3.2.0` does not rely on a `latexmkrc` file anymore. Instead, you can use `texlab.build.forwardSearchAfter: true` to keep the viewer synchronized with the cursor position. The cursor position is guessed by `texlab` by taking a look at the last edit and completion/hover positions. Note that this may not always be 100% accurate, but for most cases it should suffice. Please take a look at https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md for more information.
