### ISSUE TITLE
The site texlab.netlify.app is redirected to github.com/latex-lsp/texlab

### ISSUE THREAD

**Issue by ROCKTAKEY** [latex-lsp/texlab#466]
Hi! Thanks for this great language server!

When I access texlab.netlify.app/*, it is redirected to github.com/latex-lsp/texlab.
The site before is closed? Which document should I link from site, like [lsp-latex document](https://github.com/ROCKTAKEY/lsp-latex)?

**Comment by pfoerster** [comment]
> The site before is closed?

Yes, a lot of the users did not know about the website and just used the GitHub page instead. That's why we now host our documentation here. It can be found inside the [`docs`](https://github.com/latex-lsp/texlab/tree/master/docs) folder so I recommend linking to our GitHub page. In addition to that, it makes contributing documentation a lot easier.

**Comment by ROCKTAKEY** [comment]
I see. Thanks!
