### ISSUE TITLE
Master fails to build

### ISSUE THREAD

**Issue by petr-tik** [latex-lsp/texlab#468]
Wanted to build and install from source and ran into this build error.

```bash
petr_tik@merluzon:~/Coding/texlab master $
RUSTC_WRAPPER= cargo install --path .
  Installing texlab v3.2.0 (/home/petr_tik/Coding/texlab)
    Updating crates.io index
    Updating git repository `https://github.com/cormacrelf/citeproc-rs`
   Compiling texlab v3.2.0 (/home/petr_tik/Coding/texlab)
error[E0599]: no function or associated item named `new_immediate` found for trait object `dyn Watcher` in the current scope
  --> src/workspace/watch.rs:35:32
   |
35 |         let watcher = Watcher::new_immediate(move |event: notify::Result<notify::Event>| {
   |                                ^^^^^^^^^^^^^ function or associated item not found in `dyn Watcher`

error: aborting due to previous error
```

Curiously enough, rust-analyzer finds the definition of `Watcher::new_immediate` successfully. 

`cargo test` passes all tests, which suggests that it would make sense to add `cargo build --release` to the pre-merge pipeline after fixing master

**Comment by clason** [comment]
Texlab master builds perfectly fine for me with `cargo build --release`. I suspect your Rust might be too old (required is at least 1.51.0).

If you report build errors (in particular), you always _need to_ mention your environment (platform, architecture, `cargo --version`, relevant environment variables...)

**Comment by pfoerster** [comment]
Thanks for the report. The problem is the use of `cargo install` without the `--locked` flag. By default `cargo install` does not use the `Cargo.lock` file, which is necessary because the newest version of `notify` contains breaking changes. You can take a look at [this issue](https://github.com/rust-lang/cargo/issues/7169) over at the `cargo` repository. If you are installing a bin crate, you almost always want to use `--locked`.

**Comment by petr-tik** [comment]
Thanks for clarifying! You were right. Excuse the inconvenience and thanks for triaging what was a rather opaque bug report.
