### ISSUE TITLE
Forward search after build not working properly

### ISSUE THREAD

**Issue by embie27** [latex-lsp/texlab#475]
I use this language server together with neovim. The forward search on its on works as expected but the forward search after build does not. I have enabled the `forwardSearchAfter` option and the forward search is executed after the build but it always uses the line number `1`. This is not the case when triggering the forward search manually.

**Comment by clason** [comment]
Could you share your neovim LSP configuration?

**Comment by clason** [comment]
I think the issue is that the `textDocument/build` request does not take a `PositionParam` (only a `TextDocumentIdentifier`), so the followup `forwardSearch` command triggered from `build` doesn't have that information and only passes the file name.

(You can see that in multifile project: The forward search goes to the first line of the subfile from which you trigger the build.)

**Comment by embie27** [comment]
Sorry for the delay. This is my config for the lsp:
```
 tex.lsp.setup.settings = {
  texlab = {
    build = {
      executable = "latexmk",
      args = { "-xelatex", "-interaction=nonstopmode", "-synctex=1", "%f" },
      forwardSearchAfter = true,
      onSave = true
    },
    forwardSearch = {
      executable = "okular",
      args = { "--unique", "file:%p#src:%l%f" }
    }
  }
}
```

But by your second answer I assume that there currently is no way to go to the correct line after build only by using lsp features?

**Comment by clason** [comment]
Yes, sorry, my first comment was from before I did a bit of digging myself. You are right that (if I am correct) this requires a (minor) change in texlab to work.

**Comment by pfoerster** [comment]
Just as @clason said, I think it is best to add an (optional) line number to the `textDocument/build` request (`TextDocumentPositionParams` instead of `TextDocumentIdentifier`). At the moment, `texlab` tries to guess your current line number by taking a look at the recent edits, hovers and completions but this won't work if you are just looking at the file. Unfortunately, the client has to send this kind of extra information to the build request because you cannot query the cursor position using the standard LSP protocol.

**Comment by clason** [comment]
Yeah, but at least for Neovim, I know how to (and will) do that ;)

**Comment by pfoerster** [comment]
> Unfortunately, the client has to send this kind of extra information to the build request

Now, it is finally possible to pass the cursor position directly to the build request :)
