### ISSUE TITLE
Question: role of `rootDirectory`

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#509]
There's been a bit of discussion about what Neovim should be sending as `rootDirectory` by default. To make a reasoned case for my point of view, I thought I'd ask about what exactly texlab is using the `rootDirectory` for, when it is specified:

* Is it only used for finding the root file in a multi-file project (vulgo "`main.tex`"), or is it also used for other things (like populating non-project `workspace` or setting the build directory)?
* If it is set, does it
1. _override_ the internal detection logic or
2. provide a fallback _if_ the internal detection logic fails?
* If Neovim were to set a non-`null` default `rootDirectory`, what would be the most useful for `texlab`?

**Comment by pfoerster** [comment]
> Is it only used for finding the root file in a multi-file project (vulgo "main.tex"), or is it also used for other things (like populating non-project workspace or setting the build directory)?

At the moment, `rootDirectory` is mainly used for "expanding" the workspace. Whenever you open or change a file, `texlab` tries to find out all files which belong to the "project". It uses the following algorithm:

``` 
// expand parents
for each document in all_documents do
  while document does not have a parent do
    recursively walk up the directory tree of document and load all documents in the current folder

// expand children
for each document in all_documents do
  let links be the list of all files that document could reference
  for each link in links do
    if the target of link exists then
      load the target of link
      break

```

The interesting bits are the following:
1. A parent of a child document is defined as another document which has an (indirect) link to the child document
2. The links of a document are calculated using this method:
   - "implicit links": These are aux and log files. There are three possible locations to try out:
      1. The same directory as the document (just replacing the extension)
      2. `<working_directory>/<root_directory>/<file_name>`
      3. `<working_directory>/<aux_directory>/<file_name>`
   - "explicit links": Usually stuff you include directly (TeX files, local packages, ...). If a `rootDirectory` is set, then `texlab` searches in the directory `<working_directory>/<root_directory>`, otherwise, the same directory as the analyzed file is used.

> If Neovim were to set a non-null default rootDirectory, what would be the most useful for texlab?

Usually, `null` is sufficient. The setting mostly covers the use case, where the source directory and the working directory (the directory from which you compile) are different. In this case, `rootDirectory` should be the source directory.

**Comment by clason** [comment]
Thank you, that explains this quite clearly! So basically setting the `rootDirectory` will never be _worse_ (regarding finding all project files) than leaving it at `null`? (Currently, `nvim_lspconfig` sets this to "current directory" (of edited file); it's been proposed to change that to "first parent directory that contains a `.git` directory.)

> Usually, null is sufficient. The setting mostly covers the use case, where the source directory and the working directory (the directory from which you compile) are different. In this case, rootDirectory should be the source directory.

What would be the "working directory" from the point of texlab/the editor? The directory of the currently edited file? Or the `pwd` you start the editor from (which could be somewhere completely different, e.g., `~`)?

**Comment by pfoerster** [comment]
>  So basically setting the rootDirectory will never be worse (regarding finding all project files) than leaving it at null? 

Not quite at the moment. It won't harm the detection of the "implicit links" like aux and log files but in the case of "explicit links" will only search in `<working_directory>/<root_directory>` and not the directory of the file.
However, it should be easy to change this behavior. One problem could be a (likely very small) performance regression because you have to allocate more URIs this way but I think this should be negligible.
I can make a PR in the next days to see if it makes a difference.

> Currently, nvim_lspconfig sets this to "current directory" (of edited file)

This is basically the same as setting it to `null` so I think it is better to leave it out to improve the performance slightly (less places that need to be searched).

> it's been proposed to change that to "first parent directory that contains a .git directory.

This can be a good alternative and should work in a lot of cases. I think setting to the first parent directory that contains a .git directory (otherwise `null`) should be a good default.

> What would be the "working directory" from the point of texlab/the editor? The directory of the currently edited file? Or the pwd you start the editor from (which could be somewhere completely different, e.g., ~)?

It's the directory from which the server is started (usually this property is inherited from the client so it is equivalent to `pwd`).

**Comment by clason** [comment]
Thanks! That clears that up. (I've never had `texlab` _not_ detect a file/project root even when setting `rootDirectory` to `null` -- independent of where I was starting the editor -- so I was a bit confused...)

I don't think `texlab` needs to change anything.

> This can be a good alternative and should work in a lot of cases. I think setting to the first parent directory that contains a .git directory (otherwise null) should be a good default.

My knee-jerk reaction was that `.git` is not really LaTeX specific so not a good default; probably looking for a `.latexmkrc` would fit better...
