### ISSUE TITLE
Clean command?

### ISSUE THREAD

**Issue by bbaserdem** [latex-lsp/texlab#607]
Feel free to close this issue if I'm misunderstanding. But as far as I understand; there is no way to run a unique clean command from texlab. Would this be a feature of interest?

My usecase is that I almost completely replaced vimtex with Texlab and nvim LSP; but the only way I can clean build is running a vimtex command.

**Comment by pfoerster** [comment]
> But as far as I understand; there is no way to run a unique clean command from texlab.

No, at the moment there is no dedicated clean command.

> Would this be a feature of interest?

Usually, I do not recommend cleaning out the auxiliary files with commands like `latexmk -c` because `texlab` needs the files to implement these features:

- Diagnostics reporting for compilation errors (`log` file)
- Retrieve the numbers of labels to show them during completion and hover requests (`aux` file).

Note that you can configure `latexmk` to output the artifacts to another directory if you want to keep your main directory clean
(use the `-output-directory` flag of `latexmk` and the `texlab.auxDirectory` setting of `texlab`).

**Comment by clason** [comment]
In general I agree; however, it does happen from time to time that an `aux` file is corrupted or in a non-recoverable state so that LaTeX (and possibly texlab) gets confused and won't compile until the offending `aux` files are removed -- which would of course be (a bit) more convenient with a built-in command.

(Typical, but by far not only, example is switching from bibtex to biblatex or vice versa.)

**Comment by pfoerster** [comment]
> it does happen from time to time that an aux file is corrupted or in a non-recoverable state

That's a fair point. Would two commands accessible via `workspace/executeCommand` suffice (one for removing auxiliary files and one for removing the artifacts too)?

**Comment by clason** [comment]
> Would two commands accessible via workspace/executeCommand suffice (one for removing auxiliary files and one for removing the artifacts too)?

Sure! I don't see any need beyond the equivalent of `latexmk -c <main file>` and `latexmk -C <main file>`.

**Comment by bbaserdem** [comment]
> > But as far as I understand; there is no way to run a unique clean command from texlab.
> 
> No, at the moment there is no dedicated clean command.
> 
> > Would this be a feature of interest?
> 
> Usually, I do not recommend cleaning out the auxiliary files with commands like `latexmk -c` because `texlab` needs the files to implement these features:
> 
> * Diagnostics reporting for compilation errors (`log` file)
> * Retrieve the numbers of labels to show them during completion and hover requests (`aux` file).
> 
> Note that you can configure `latexmk` to output the artifacts to another directory if you want to keep your main directory clean (use the `-output-directory` flag of `latexmk` and the `texlab.auxDirectory` setting of `texlab`).

The output directory flag of latexmk only works on miktex. I use texlive distribution myself so never got around to using it; but don't mind auxillary files being distributed around.

(Bear in mind; this is not a feature that I actively need so not a big issue to not have. Just that I noticed that I there was no equivalent when I was porting my keybinds from vimtex to texlab.)

> > Would two commands accessible via workspace/executeCommand suffice (one for removing auxiliary files and one for removing the artifacts too)?
> 
> Sure! I don't see any need beyond the equivalent of `latexmk -c <main file>` and `latexmk -C <main file>`.

That would be exactly what I would be looking for.

**Comment by bbaserdem** [comment]
I'm unfamiliar with how to work with lsp server directly; can anyone point me towards the command for a neovim instance with nvim-lspconfig?

**Comment by clason** [comment]
You will have to implement it yourself. Look at the build and forward search commands; it's not hard.

**Comment by pfoerster** [comment]
The commands are now part of `v4.1.0`
