### ISSUE TITLE
Possible to ship on CTAN?

### ISSUE THREAD

**Issue by AntoinePrv** [latex-lsp/texlab#64]
Hello,

Thank you for this great project.
Do you think it would be possible to ship texlab on CTAN?
I do not have any experience with CTAN, and shipping binaries might even be more complex.

I just wanted to start the discussion, maybe you were already thinking about this.

**Comment by efoerster** [comment]
Thanks for the suggestion. We will look into this soon, should be not too hard to upload it.

**Comment by 9999years** [comment]
I have [a few packages uploaded on CTAN](https://ctan.org/author/turner) and would be glad to answer questions. 🙂

**Comment by clason** [comment]
@efoerster Since the binaries are statically compiled, it might be enough to just upload a README and the three built binaries to https://www.ctan.org/tex-archive/support via https://www.ctan.org/upload

(For texlive to include it from there, more is required, see https://www.tug.org/texlive/pkgcontrib.html)

**Comment by efoerster** [comment]
We are on CTAN now: https://ctan.org/pkg/texlab

**Comment by clason** [comment]
@efoerster Nice! Would it make sense to also upload the corresponding build artifacts (from the release tab)? That would make it easier for user, I think (since the binaries are monolithic and should thus work on most systems).

Are you planning on getting it downstreamed to texlive as well?
