### ISSUE TITLE
Build on save not triggered by write by neovim autocmd

### ISSUE THREAD

**Issue by cs-ehanc001** [latex-lsp/texlab#821]
I am having an issue where automatic build on save is not occurring after a write called by a neovim autocmd.
Manually writing the file triggers the build and forward search as expected.
If this is actually an issue with nvim-lsp, I apologize.

Expected outcome: (automatic write)
- [x] Autocmd at the bottom of this issue triggers a write
- [x] Texlab automatic build is triggerd, updating pdf output
- [x] Forward search is performed

Actual outcome:
- [x] Autocmd at the bottom of this issue triggers a write
- [ ] Texlab automatic build is triggerd, updating pdf output
- [ ] Forward search is performed

Expected outcome: (manual write (`:w<CR>`))
- [x] Autocmd at the bottom of this issue triggers a write
- [x] Texlab automatic build is triggerd, updating pdf output
- [x] Forward search is performed

Actual outcome:
- [x] Autocmd at the bottom of this issue triggers a write
- [x] Texlab automatic build is triggerd, updating pdf output
- [x] Forward search is performed

Configuration for texlab, through nvim's lspconfig:
```
require'lspconfig'.texlab.setup{
  cmd = {"texlab"},
  filetypes = {"tex", "plaintex", "bib"},
  single_file_support = true,
  settings = {
    texlab = {
      auxDirectory = ".",
      bibtexFormatter = "texlab",
      build = {
        executable = "pdflatex",
        forwardSearchAfter = true,
        onSave = true
      },
      chktex = {
        onEdit = true,
        onOpenAndSave = true
      },
      diagnosticsDelay = 100,
      formatterLineLength = 500,
      diagnostics = {
        ignoredPatterns = {".*may.*"}
      },
      forwardSearch = {
        executable = "zathura",
        args = {"--synctex-forward", "%l:1:%f", "%p"}
      },
      latexFormatter = "latexindent",
      latexindent = {
        modifyLineBreaks = false
      }
    }
  }
}
```

Autocmd that triggers a write which is not triggering build:
`autocmd InsertLeave,TextChanged *.tex :write`

**Comment by pfoerster** [comment]
@cs-ehanc001 I am not familiar with the way the `autocmd` works but I assume that the following happens:

- In the version *without* the `autocmd`, the write command triggers a `textDocument/didSave` notification, which is sent to `texlab` through `nvim-lsp`. `texlab` then triggers a build including a forward search using the document mentioned in the notification.
- In the version *with* the `autocmd`, the LSP layer is probably bypassed and does not cause a `textDocument/didSave` notification so there is no build.

Theoretically, the server could know that the document was saved because it listens to file events (mostly to reparse the log files) but triggering a build based on file events can be error-prone because the save operation might result in multiple events (debouncing should help here though).

I think the easiest way to fix this is to get the `autocmd` to trigger a LSP save notification.
