### ISSUE TITLE
Inlay hints are not showing in VSCode

### ISSUE THREAD

**Issue by czeidler** [latex-lsp/texlab#903]
From looking at the source code it seems like there should be inlay hints for label references, is this correct? For example, for 

```tex
\section{Section1}
\label{section1}
Some text...

\section{Section 2}

\begin{figure}
    \centering
      \includegraphics[width=0.5\textwidth]{gull}
    \caption{Close-up of a gull}
    \label{fig:gull}
  \end{figure}
Figure~\ref{fig:gull} shows a photograph of a gull.

Also see Section~\ref{section1}.
```

shouldn't all the \ref or \label blocks get inlay hints? For me, I only see the plain tex, no inlay hints at all  (hover is working though).

I actually noticed this issue while working on my own language server for an unrelated project where I took texlab as a template for the language server. In my project VSCode never sends a request for inlay hints even though the server advertises that it has this capability.

Inlay hints are working for Rust and I have them enabled in VSCode. Any ideas why they are not working for texlab?

**Comment by pfoerster** [comment]
> shouldn't all the \ref or \label blocks get inlay hints?

Yes, `texlab` should show the inlay hints for the  `\label` commands (not `\ref`). However, in this case, the server won't return the inlay hints because the document was not compiled yet. It only shows the inlay hints if the labels have a number associated with them. Usually, the caption of the label is right next to the command so the server just includes the number instead.

> In my project VSCode never sends a request for inlay hints even though the server advertises that it has this capability.

That sounds a bit odd. Does it actually never send the command or is the response always empty? Can you try compiling the document so that it produces an `aux` file?

**Comment by czeidler** [comment]
Thank you, yes with the aux file the inlay hints are showing up! Very cool feature.

Will given an update when I find the cause of the issue I am having in my project...

**Comment by czeidler** [comment]
My problem was that my language server extension dependencies (e.g. `vscode-languageclient`) were completely outdated. Think I started from some, apparently very old, official tutorial project...
