### ISSUE TITLE
texlab.auxDirectory and texlab.build.auxDirectory behave differently

### ISSUE THREAD

**Issue by puppe** [latex-lsp/texlab#911]
I call latexmk with -output-directory=latexmk. Consequently, the PDF file is created in the latexmk sub-directory. I used to set
`texlab.auxDirectory` to `"latexmk"` and everything worked as expected. TexLab was able to find the compiled PDF file and passed it correctly to my PDF viewer for forward search. In the latest version, 5.8.0, `texlab.auxDirectory` has been deprecated. I tried replacing it with `texlab.build.auxDirectory` but then TexLab looks for the PDF file in the root directory. I haven‘t been able to reproduce the old bevahiour without using the old, deprecated option. Was this intended? What is the proper way to tell TexLab the location of the compiled PDF file?

**Comment by pfoerster** [comment]
@puppe
Prior to 5.8.0, `texlab` was using `texlab.auxDirectory` as the directory containing all build artifacts (`.aux`, `.log` and `.pdf` files). However, this is not flexible enough because you can change the `.aux` directory without changing the other directories (https://github.com/latex-lsp/texlab/issues/906). That's why I splitted it up in `texlab.build.logDirectory` and `texlab.build.auxDirectory`. `texlab.auxDirectory` still exists as a fallback for backwards compatibility but the new settings take precedence if they are set. 

The PDF file is searched in `texlab.build.logDirectory` currently, but I think it is more clear if we introduce an additional `texlab.build.pdfDirectory` setting (see #914).

**Comment by puppe** [comment]
I have since replaced -output-directory with -auxdir, which is what I actually wanted. Previously, I had an extra rule in my Makefile that copied the PDF to the root directory. So, I guess I learned something useful about latexmk in the process. Didn‘t know about -auxdir.

Thanks for acting so quickly on this! Looking forward to #914  being merged. Feel free to close this issue whenever you like.
