### ISSUE TITLE
Undefined References in nested files in subfolder with looped input declaration

### ISSUE THREAD

**Issue by naibaf0** [latex-lsp/texlab#930]
Hello, I am using texlab with Neovim in a project where the chapters are in separate files in a subfolder. While the root file detection seems to work (I don't get errors regarding missing begin{document} for example), I am unable to reference anything indicated with labels in different files. My chapter files are imported with a loop as follows in the root document:

```
	\foreach \i in {01,02,03,04,05,06,07,08,09,...,99} {
		\edef\FileName{content/\i chapter}
			\IfFileExists{\FileName}{
				\input{\FileName}
			}
			{
				%file does not exist
			}
	}
```

It does work when referencing each file directly with `\input{content/01chapter}` etc. instead so I will do that for now, but maybe this case can be addressed in the future.

Thanks for the great tool in any case :)

**Comment by pfoerster** [comment]
@naibaf0 Thanks for the kind words!

> but maybe this case can be addressed in the future.

Unfortunately, I don't think this will be possible because parsing this would require running the `\foreach` loop, which basically requires re-implementing the TeX engine in the general case.

`texlab` treats LaTeX as a regular programming language (although it is not) so catcode and programming constructs are not interpreted.
