### ISSUE TITLE
Using Emacs+eglot+texlab turns into a CPU at 100% with a 1000 line file

### ISSUE THREAD

**Issue by maikol-solis** [latex-lsp/texlab#986]
Hi! 

I have problem using texlab in Emacs + Eglot.  When I open a 1000 line file, every time I start the server, the CPU goes to 100%, and I cannot do anything for at least 20 seconds. Thereafter, I can start typing, but the cycle restarts again.  

![image](https://github.com/latex-lsp/texlab/assets/4078489/b3ae1a81-6fb1-494e-b23a-a4ce7967910d)

This is the installed version using homebrew. 

```
texlab --version
texlab 5.12.0
```
Here there is a sample of the process when it's at 100%. https://pastebin.com/raw/kwSAM2VE 

Thanks for your assistance. 

Best.

**Comment by maikol-solis** [comment]
Just as a reference, digestif (https://github.com/astoff/digestif) starts and stays with a decent CPU usage in this case.

**Comment by maikol-solis** [comment]
Here is the log file when the high CPU happens. I removed the actual text of the .tex file due to obvious reasons. 

[texlab_high_cpu.log](https://github.com/latex-lsp/texlab/files/13794668/texlab_high_cpu.log)

**Comment by pfoerster** [comment]
Thanks for the report! From the log, it can be seen that the server loads some parts of the (Tiny)TeX distro. This could be the cause of the high CPU usage because it results into a lot of diagnostics notifications being sent to the client. I have created a PR which disables recursively descending into the TeX distro by default. Can you give it a try and see if it resolves the issue, please? #987.

**Comment by maikol-solis** [comment]
Thanks to #987 the CPU looks normal. Here is the log file.

[texlab_normal_cpu.log](https://github.com/latex-lsp/texlab/files/13821708/texlab_normal_cpu.log)

Thanks!
